[package]
name = "meuip"
version = "0.1.0"
authors = ["Eduardo Heredia <contato@eduardoheredia.net.br>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.2", features = ["json"] }
serde = { version = "1.0.124", features = ["derive"] }
tokio = { version = "1.3.0", features = ["full"] }
